#ganache.url=http://0.0.0.0:8545
#contract.address=0xf12b5dd4ead5f743c6baa640b0216200e89b60da
#
#server.port=8083
ganache:
  url: "http://localhost:8545"

contract:
    address: "0xf12b5dd4ead5f743c6baa640b0216200e89b60da"

server:
  port: 8083



keycloak:
  realm : "your-realm-name"
  auth-server-url : "http://localhost:8080/auth"
  ssl-required : "external"
  resource : "your-client-id"
  credentials:
    secret  : "your-client-secret"
  use-resource-role-mappings : true
  principal-attribute : "preferred_username"

